```{r, table-set-up, message = FALSE}
dat <- esp_data %>%
  dplyr::ungroup() %>%
  dplyr::mutate(INDICATOR_NAME = .data$INDICATOR_NAME %>%
    stringr::str_replace_all("_", " ") %>%
    stringr::str_wrap(width = 20))
```

```{r, eco-table}
this_dat <- dat %>%
  dplyr::filter(INDICATOR_TYPE == "Ecosystem")

AKesp::esp_traffic_tab(
  data = this_dat,
  year = (params$year - 4):params$year,
  cap = paste0("First stage ecosystem indicator analysis for ", params$fish, ', including indicator title and the indicator status of the last five years. The indicator status is designated with text, (greater than = "high", less than = "low", or within 1 standard deviation = "neutral" of long-term mean). Fill color of the cell is based on the sign of the anticipated relationship between the indicator and sablefish (blue = good conditions for sablefish, red = poor conditions, white = average conditions). A gray fill and text = "missing" will appear if there were no data for that year.')
) %>%
  flextable::width(j = 2, width = 2) %>%
  flextable::width(j = c(1, 3:6), width = 0.75)
```

```{r, socio-table, eval = "Socioeconomic" %in% esp_data$INDICATOR_TYPE}
this_dat <- dat %>%
  dplyr::filter(INDICATOR_TYPE == "Socioeconomic")

AKesp::esp_traffic_tab(
  data = this_dat,
  year = (params$year - 4):params$year,
  cap = paste0("First stage socioeconomic indicator analysis for ", params$fish, ', including indicator title and the indicator status of the last five years. The indicator status is designated with text, (greater than = "high", less than = "low", or within 1 standard deviation = "neutral" of long-term mean). Fill color of the cell is based on the sign of the anticipated relationship between the indicator and sablefish (blue = good conditions for sablefish, red = poor conditions, white = average conditions). A gray fill and text = "missing" will appear if there were no data for that year.')
) %>%
  flextable::width(j = 2, width = 2) %>%
  flextable::width(j = c(1, 3:6), width = 0.75)
```
